server:
  port: 2021
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        #nacos开启权限才要账号密码,没开启可以不写
        username: nacos
        password: nacos
        namespace: test #命名空间
        ephemeral: false #永久实例 当服务下线就会将服务剔除
        #service: 默认取spring.application.name
        #group: 默认DEFAULT_GROUP 分组管理
        #weight: 权重,配合负载均衡
        #metadata: 元数据 扩展使用
        #更多具体设置,参考https://nacos.io/zh-cn/docs/system-configurations.html

#设置负载均衡策略(方法2)只针对单个服务
#stock-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    #配置饥饿加载的服务
    clients: stock-service
    #开启ribbon饥饿加载
    enabled: true
#springboot默认日志级别是info,feign的debug日志级别就不会输出
logging:
  level:
    com.cosmos.feign: debug
#Feign日志局部配置(方法2)
feign:
  client:
    config:
      stock-service:
        loggerLevel: BASIC
        #设置契约配置(兼容旧版Feign注解,一般在升级旧版系统用)
        #contract: feign.Contract.Default
        #连接超时时间(调用接口时间超时)
        #connectTimeout: 5000
        #自定义拦截器
        #requestInterceptors[0]: com.cosmos.feign.interceptor.CustomFeignInterceptor