server:
  port: 2022
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: stock
        password: cosmos
        namespace: test #命名空间
        ephemeral: false #永久实例